### ISSUE TITLE
Questions, questions...

### ISSUE THREAD

**Issue by danielearwicker** [akshat1/compute#4]
In README it gives the example:

```
var x = C.o(7);
var y = C.o(22);
var z = C.from(x, y function(x1, y1){
    return y1/x1;
});
z(); //undefined, because neither x nor y have changed
z.$fire();
z(); //3.14 .... blah ....
```

(I think there's a missing comma in `x, y function`...)

But in Knockout:

```
var x = ko.observable(7);
var y = ko.observable(22);
var z = ko.pureComputed((x1, y1) => y1/x1);
z(); // NOT undefined!
```

`ko.computed` (or better: `ko.pureComputed`) has a well-defined value as soon as it is declared. Why does your version behave differently?

Is `Compute.from` like `ko.computed`, or is it like `ko.pureComputed`?

Why is it necessary to declare the dependencies upfront? In knockout we can just call an observable to get its value and it is automatically tracked as one of our dependencies. This means we can call helper functions which internally access observables and these will also be automatically tracked.

If your implementation doesn't work that way, then the behaviour will be different if you switch to using Knockout in the browser.

**Comment by danielearwicker** [comment]
Never mind - I just created https://github.com/danielearwicker/kor which is just Knockout with everything removed except the observables/computed stuff.

**Comment by akshat1** [comment]
1. Readme syntax error: You are right, there is indeed a comma missing. Thanks for the heads up.
2. Compute.from behavior
   I did not look at ko.computed or pureComputed while writing Compute.from. Compute.from does not have a value as soon as it is defined because in my personal experience, the source observables often don't have a value at the time the relationship is defined (often the values will be fetched via xhr or some other mechanism). Calling the evaluation function immediately in such a situation just causes a useless execution. On the other hand, the return value is chainable, so one can do

<pre><code>
var x = C.o(7);
var y = C.o(22);
var z = C.from(x, y, function(x1, y1){return x/y;}).$fire(); 
</code></pre>

"Why is it necessary to declare the dependencies upfront? In knockout we can just call an observable to get its value and it is automatically tracked as one of our dependencies. This means we can call helper functions which internally access observables and these will also be automatically tracked. If your implementation doesn't work that way, then the behaviour will be different if you switch to using Knockout in the browser."

I'm assuming that by declaring dependencies you mean enumerating the source observables in C.from. I like to do this because it seems cleaner overall to me. Consider

<pre><code>
var MyFuncLibrary = {
.
  myAwesomeCalculation: function(x, y, z){
    return x + y + z;
  },
  anotherAwesomeCalculation: function(x, y, z) {
    return x * y * z;
  }
.
.
.
};
</code></pre>

I can use these functions in a C.from in multiple modules, or use them without observables entirely. This may not be important, or even relevant for some (or most) projects, but it made sense for some stuff that I have been building and I spun it off as a separate library thinking that it might be useful for someone else :)

For situations where one wants the same behavior as ko.computed one could probably just use ko, considering that ko is not a big framework (size-wise), and is available for the browser as well as node. Your fork makes it even easier to do so.

Thanks for trying Compute, and please feel free to add comments if you feel something could be done better in a different way. And best of luck with kor!
